services:
  server:
    image: demo/server:latest
    container_name: server
    # Ensure database is healthy before starting server
    depends_on:
      database:
        condition: service_healthy
    build:
    # build from Dockerfile in Task1
      context: ../Task1
      dockerfile: Dockerfile
    # build with argument mode=dev
      args:
        mode: dev
    # Add env variable LOG_LEVEL and database related variables
    environment:
      LOG_LEVEL: debug
      POSTGRES_DB: demo
      PGUSER: demouser
      PGPASSWORD: password123
    # Run command at startup
    command: uvicorn main:app --reload
    # Mount volume for local data
    volumes:
      - ../Task3:/mnt
  database:
    image: postgres:13
    container_name: database
    restart: always
  # Provide environments for initilization
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: password123
  # Healthcheck for database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demouser -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Mount volumes for db data 
    volumes:
      - db-data:/var/lib/pgsql/data
volumes:
  db-data: