name: Test, build and push image
on: 
    push:
        paths:
            - .github/workflows/*
            - Task1/*
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.17'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi sqlmodel httpx psycopg2-binary
      - name: Run tests
        run: |
          pytest Task1/tests.py
  build_push_image:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: ./Task1
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-postgres:latest